services:
  - type: web
    name: 1recom-app
    env: node
    plan: starter
    buildCommand: npm ci --only=production --no-audit --no-fund && npm install --production=false --no-audit --no-fund && npm run build
    startCommand: npm run start:production
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
