services:
  - type: web
    name: recom-mqxd
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run start:production
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: APP_VERSION
        value: 1.0.0
      - key: NGROK_URL
        value: https://vigorously-loving-pug.ngrok-free.app
      - key: RENDER_URL
        value: https://recom-mqxd.onrender.com
      - key: ALLOWED_ORIGINS
        value: http://localhost:3000,http://localhost:5173,https://vigorously-loving-pug.ngrok-free.app,https://recom-mqxd.onrender.com
      - key: RATE_LIMIT_WINDOW_MS
        value: 1000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 10
      - key: LOG_LEVEL
        value: combined
      - key: CUSTOM_JS_URL
        value: https://ec.1nax.app/ec.js
      - key: CUSTOM_CSS_URL
        value: https://ec.1nax.app/ec.css
    healthCheckPath: /api/health
    autoDeploy: true
    branch: main
